<a href="https://colab.research.google.com/github/KaihangZhao/DL_Notebook_Warehouse/blob/main/Isolation_forest_anomaly_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! unzip creditcard.csv.zip

Archive:  creditcard.csv.zip
  inflating: creditcard.csv          


In [ ]:
from sklearn.ensemble import IsolationForest
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

In [ ]:
data = pd.read_csv('creditcard.csv')



scalar = StandardScaler()

X = data.drop('Class', axis=1)
y = data.Class

X_train_v, X_test, y_train_v, y_test = train_test_split(X, y, 
                                                    test_size=0.3, random_state=42)
X_train, X_validate, y_train, y_validate = train_test_split(X_train_v, y_train_v, 
                                                            test_size=0.2, random_state=42)

X_train = scalar.fit_transform(X_train)
X_validate = scalar.transform(X_validate)
X_test = scalar.transform(X_test)

clf = IsolationForest(contamination= 0.00172, n_jobs=-1).fit(X_train)

In [ ]:


def print_score(label, prediction, train=True):
    if train:
        clf_report = pd.DataFrame(classification_report(label, prediction, output_dict=True))
        print("Train Result:\n================================================")
        print(f"Accuracy Score: {accuracy_score(label, prediction) * 100:.2f}%")
        print("_______________________________________________")
        print(f"Classification Report:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(y_train, prediction)}\n")
        
    elif train==False:
        clf_report = pd.DataFrame(classification_report(label, prediction, output_dict=True))
        print("Test Result:\n================================================")        
        print(f"Accuracy Score: {accuracy_score(label, prediction) * 100:.2f}%")
        print("_______________________________________________")
        print(f"Classification Report:\n{clf_report}")
        print("_______________________________________________")
        print(f"Confusion Matrix: \n {confusion_matrix(label, prediction)}\n") 

In [ ]:
y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)
y_train_pred = np.where(y_train_pred==1,0,1)
y_test_pred = np.where(y_test_pred==1,0,1)
print_score(y_train, y_train_pred, train=True)
print_score(y_test, y_test_pred, train=False)

Train Result:
Accuracy Score: 99.73%
_______________________________________________
Classification Report:
                       0           1  accuracy      macro avg   weighted avg
precision       0.998606    0.236364  0.997291       0.617485       0.997234
recall          0.998681    0.226481  0.997291       0.612581       0.997291
f1-score        0.998643    0.231317  0.997291       0.614980       0.997263
support    159204.000000  287.000000  0.997291  159491.000000  159491.000000
_______________________________________________
Confusion Matrix: 
 [[158994    210]
 [   222     65]]

Test Result:
Accuracy Score: 99.78%
_______________________________________________
Classification Report:
                      0           1  accuracy     macro avg  weighted avg
precision      0.998910    0.307143  0.997776      0.653026      0.997809
recall         0.998863    0.316176  0.997776      0.657520      0.997776
f1-score       0.998886    0.311594  0.997776      0.655240      0.997792


In [ ]:
clf = IsolationForest(contamination= 0.05, n_jobs=-1).fit(X_train)
y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)
y_train_pred = np.where(y_train_pred==1,0,1)
y_test_pred = np.where(y_test_pred==1,0,1)
print_score(y_train, y_train_pred, train=True)
print_score(y_test, y_test_pred, train=False)

Train Result:
Accuracy Score: 95.12%
_______________________________________________
Classification Report:
                       0           1  accuracy      macro avg   weighted avg
precision       0.999677    0.029843  0.951182       0.514760       0.997931
recall          0.951402    0.829268  0.951182       0.890335       0.951182
f1-score        0.974942    0.057613  0.951182       0.516278       0.973291
support    159204.000000  287.000000  0.951182  159491.000000  159491.000000
_______________________________________________
Confusion Matrix: 
 [[151467   7737]
 [    49    238]]

Test Result:
Accuracy Score: 95.15%
_______________________________________________
Classification Report:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999729    0.026912    0.9515      0.513321      0.998181
recall         0.951680    0.838235    0.9515      0.894958      0.951500
f1-score       0.975113    0.052150    0.9515      0.513632      0.973644


In [ ]:
clf = IsolationForest(contamination= 0.1, n_jobs=-1).fit(X_train)
y_train_pred = clf.predict(X_train)
y_test_pred = clf.predict(X_test)
y_train_pred = np.where(y_train_pred==1,0,1)
y_test_pred = np.where(y_test_pred==1,0,1)
print_score(y_train, y_train_pred, train=True)
print_score(y_test, y_test_pred, train=False)

Train Result:
Accuracy Score: 90.14%
_______________________________________________
Classification Report:
                       0           1  accuracy      macro avg   weighted avg
precision       0.999763    0.015863  0.901374       0.507813       0.997993
recall          0.901410    0.881533  0.901374       0.891471       0.901374
f1-score        0.948042    0.031165  0.901374       0.489604       0.946392
support    159204.000000  287.000000  0.901374  159491.000000  159491.000000
_______________________________________________
Confusion Matrix: 
 [[143508  15696]
 [    34    253]]

Test Result:
Accuracy Score: 90.13%
_______________________________________________
Classification Report:
                      0           1  accuracy     macro avg  weighted avg
precision      0.999857    0.014620  0.901268      0.507238      0.998289
recall         0.901239    0.919118  0.901268      0.910178      0.901268
f1-score       0.947990    0.028782  0.901268      0.488386      0.946527
